-- 0005_seed_trip_hazard.sql
-- Adds a seed-only "trip_hazard" report type for Cornell's Trip Hazards
-- layer (CLAUDE.md §6; plan §10.5): the plan's 7 report types don't cover
-- facilities trip-hazard data loaded as seed reports. Paste after 0001-0004.

-- ---------------------------------------------------------------------------
-- Replace the `type` check constraint on public.reports. Its name is
-- auto-generated by Postgres (not hand-named in 0001_tables.sql), so it's
-- looked up via pg_constraint by which column it covers, rather than
-- guessed by naming convention.
-- ---------------------------------------------------------------------------
do $$
declare
    v_type_attnum smallint;
    v_constraint_name text;
begin
    select attnum into v_type_attnum
    from pg_attribute
    where attrelid = 'public.reports'::regclass
      and attname = 'type';

    if v_type_attnum is null then
        raise exception 'public.reports has no column named "type"';
    end if;

    select con.conname into v_constraint_name
    from pg_constraint con
    where con.conrelid = 'public.reports'::regclass
      and con.contype = 'c'
      and v_type_attnum = any(con.conkey)
    limit 1;

    if v_constraint_name is null then
        raise exception 'could not find a check constraint on public.reports(type)';
    end if;

    execute format('alter table public.reports drop constraint %I', v_constraint_name);
end
$$;

alter table public.reports
    add constraint reports_type_check
    check (type in (
        'blocked_path', 'ice', 'construction', 'too_steep',
        'too_dark', 'too_loud', 'crowded', 'trip_hazard'
    ));

-- trip_hazard is seed-only: it represents Cornell's undated historical trip
-- hazard inventory (plan §10.5), never a client-submitted live report.
alter table public.reports
    add constraint reports_trip_hazard_seed_only
    check (type <> 'trip_hazard' or source = 'seed');
